import { Montserrat, Playfair } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.css';
import Footer from '@/components/Footer';
import Header from '@/components/Header';

const playfair = Playfair({
  subsets: ['latin'],
  variable: '--font-playfair',
  axes: ['opsz', 'wdth']
});

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['400', '500', '700']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${montserrat.variable} ${playfair.variable} bg-offWhite text-darkGray`}
    >
      <body className='font-sans'>
        <Header />
        <main className='flex flex-col items-center justify-between gap-14'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
